# Generated by Django 6.0.3 on 2026-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_remove_booking_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='excursion_type',
            field=models.CharField(choices=[('AIR_SAFARI', 'Air Safari'), ('ROAD_SAFARI', 'Road Safari')], default='ROAD_SAFARI', max_length=20),
        ),
    ]
