# Generated by Django 6.0.3 on 2026-04-03 09:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('operations', '0008_excursion_excursion_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=20)),
                ('category_label', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleCategoryAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
                ('manual_blocked_count', models.PositiveIntegerField(default=0)),
                ('reserved_count', models.PositiveIntegerField(default=0)),
                ('confirmed_count', models.PositiveIntegerField(default=0)),
                ('cancelled_count', models.PositiveIntegerField(default=0)),
                ('released_count', models.PositiveIntegerField(default=0)),
                ('remaining_capacity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['participant_category__label'],
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='booking',
            name='amendment_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by_type',
            field=models.CharField(blank=True, choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='inventory_released_on_cancel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded'), ('NOT_APPLICABLE', 'Not applicable')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded'), ('NOT_APPLICABLE', 'Not applicable')], default='NOT_APPLICABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('WEBSITE', 'Website'), ('OTA', 'OTA'), ('API', 'API'), ('MANUAL_OFFICE', 'Manual office entry'), ('LEGACY', 'Legacy')], default='MANUAL_OFFICE', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='supplier_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='voucher_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('AMENDED', 'Amended')], default='CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('SAFARI', 'Safari'), ('EXCURSION', 'Excursion'), ('TRANSFER', 'Transfer'), ('PACKAGE', 'Package'), ('HOTEL_ADD_ON', 'Hotel Add-on'), ('ACTIVITY', 'Activity'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('duration_text', models.CharField(blank=True, max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('inclusions', models.TextField(blank=True)),
                ('exclusions', models.TextField(blank=True)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('booking_cutoff_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('pricing_mode', models.CharField(choices=[('PER_PERSON', 'Per person'), ('PER_GROUP', 'Per group'), ('COLLECTIVE_FIXED', 'Collective / fixed')], default='PER_PERSON', max_length=30)),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('default_currency', models.CharField(default='KES', max_length=3)),
                ('default_timezone', models.CharField(default='Africa/Nairobi', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_excursion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_products', to='operations.excursion')),
                ('legacy_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_products', to='operations.package')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='operations.product'),
        ),
        migrations.CreateModel(
            name='ProductParticipantCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('ADULT', 'Adult'), ('CHILD', 'Child'), ('INFANT', 'Infant'), ('SENIOR', 'Senior'), ('STUDENT', 'Student'), ('GROUP', 'Group'), ('COLLECTIVE', 'Collective')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('uses_inventory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_categories', to='operations.product')),
            ],
            options={
                'ordering': ['product__name', 'label'],
            },
        ),
        migrations.CreateModel(
            name='BookingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=20)),
                ('category_label', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_quantities', to='operations.booking')),
                ('participant_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_lines', to='operations.productparticipantcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('schedule_type', models.CharField(choices=[('FIXED_DATE', 'Fixed date departure'), ('RECURRING', 'Recurring schedule'), ('TIME_POINT', 'Time-point departure'), ('TIME_PERIOD', 'Time-period access')], default='FIXED_DATE', max_length=20)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('access_window_start', models.TimeField(blank=True, null=True)),
                ('access_window_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=64)),
                ('recurrence_rule', models.TextField(blank=True)),
                ('recurrence_days', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD_OUT', 'Sold out'), ('CANCELLED', 'Cancelled'), ('PAUSED', 'Paused')], default='AVAILABLE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('guide_assignment', models.CharField(blank=True, max_length=255)),
                ('vehicle_assignment', models.CharField(blank=True, max_length=255)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
                ('manual_blocked_count', models.PositiveIntegerField(default=0)),
                ('reserved_count', models.PositiveIntegerField(default=0)),
                ('confirmed_count', models.PositiveIntegerField(default=0)),
                ('cancelled_count', models.PositiveIntegerField(default=0)),
                ('released_count', models.PositiveIntegerField(default=0)),
                ('remaining_capacity', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='operations.product')),
            ],
            options={
                'ordering': ['start_at', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='operations.productschedule'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('CONVERTED', 'Converted')], default='ACTIVE', max_length=20)),
                ('customer_full_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('hold_expires_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('internal_comments', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('audit_trail', models.JSONField(blank=True, default=list)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by_type', models.CharField(blank=True, choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reservations', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='clients.client')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='operations.product')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='operations.productschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingAuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('SCHEDULE', 'Schedule'), ('RESERVATION', 'Reservation'), ('BOOKING', 'Booking')], max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='operations.booking')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='operations.productschedule')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='operations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_booking', to='operations.reservation'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_days__gte', 1)), name='booking_days_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('num_adults__gte', 0)), name='booking_adults_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('num_children__gte', 0)), name='booking_children_non_negative'),
        ),
        migrations.AddField(
            model_name='reservationparticipant',
            name='participant_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_lines', to='operations.productparticipantcategory'),
        ),
        migrations.AddField(
            model_name='reservationparticipant',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='operations.reservation'),
        ),
        migrations.AddField(
            model_name='schedulecategoryavailability',
            name='participant_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_availability', to='operations.productparticipantcategory'),
        ),
        migrations.AddField(
            model_name='schedulecategoryavailability',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_availability', to='operations.productschedule'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('booking_cutoff_minutes__gte', 0)), name='product_booking_cutoff_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productparticipantcategory',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='product_category_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='bookingparticipant',
            constraint=models.UniqueConstraint(fields=('booking', 'category_code'), name='booking_category_unique'),
        ),
        migrations.AddConstraint(
            model_name='productschedule',
            constraint=models.CheckConstraint(condition=models.Q(('total_capacity__gte', 0)), name='schedule_total_capacity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productschedule',
            constraint=models.CheckConstraint(condition=models.Q(('manual_blocked_count__gte', 0)), name='schedule_blocked_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productschedule',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_count__gte', 0)), name='schedule_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productschedule',
            constraint=models.CheckConstraint(condition=models.Q(('confirmed_count__gte', 0)), name='schedule_confirmed_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productschedule',
            constraint=models.CheckConstraint(condition=models.Q(('cancelled_count__gte', 0)), name='schedule_cancelled_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productschedule',
            constraint=models.CheckConstraint(condition=models.Q(('released_count__gte', 0)), name='schedule_released_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productschedule',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_capacity__gte', 0)), name='schedule_remaining_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('hold_expires_at__isnull', False)), name='reservation_hold_required'),
        ),
        migrations.AddConstraint(
            model_name='reservationparticipant',
            constraint=models.UniqueConstraint(fields=('reservation', 'category_code'), name='reservation_category_unique'),
        ),
        migrations.AddConstraint(
            model_name='schedulecategoryavailability',
            constraint=models.UniqueConstraint(fields=('schedule', 'participant_category'), name='schedule_participant_category_unique'),
        ),
    ]
