# Generated by Django 6.0.3 on 2026-04-03 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_backfill_products_and_booking_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_name', models.CharField(default='STANDARD', max_length=100)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('KES', 'Kenya Shilling')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='operations.productparticipantcategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='operations.product')),
            ],
            options={
                'ordering': ['product__name', 'currency', 'rate_name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'participant_category', 'rate_name', 'currency'), name='product_price_unique_rate_currency')],
            },
        ),
    ]
