# Generated by Django 6.0.3 on 2026-04-03 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('operations', '0011_productprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiIdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('GET_YOUR_GUIDE', 'GetYourGuide'), ('VIATOR', 'Viator'), ('OTA_GENERIC', 'Generic OTA'), ('API_GENERIC', 'Generic API'), ('CUSTOM_PARTNER', 'Custom partner'), ('INTERNAL', 'Internal')], max_length=40)),
                ('event_type', models.CharField(choices=[('BOOKING_CREATE', 'Booking create'), ('BOOKING_UPDATE', 'Booking update'), ('BOOKING_CANCEL', 'Booking cancel'), ('AVAILABILITY_SYNC', 'Availability sync'), ('PRODUCT_SYNC', 'Product sync'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalProductMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('GET_YOUR_GUIDE', 'GetYourGuide'), ('VIATOR', 'Viator'), ('OTA_GENERIC', 'Generic OTA'), ('API_GENERIC', 'Generic API'), ('CUSTOM_PARTNER', 'Custom partner'), ('INTERNAL', 'Internal')], max_length=40)),
                ('external_product_id', models.CharField(max_length=255)),
                ('external_option_id', models.CharField(blank=True, max_length=255)),
                ('external_rate_id', models.CharField(blank=True, max_length=255)),
                ('external_category_code', models.CharField(blank=True, max_length=100)),
                ('external_product_name', models.CharField(blank=True, max_length=255)),
                ('external_option_name', models.CharField(blank=True, max_length=255)),
                ('default_currency', models.CharField(blank=True, max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'product__name', 'external_product_id'],
            },
        ),
        migrations.CreateModel(
            name='InboundBookingPayload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('GET_YOUR_GUIDE', 'GetYourGuide'), ('VIATOR', 'Viator'), ('OTA_GENERIC', 'Generic OTA'), ('API_GENERIC', 'Generic API'), ('CUSTOM_PARTNER', 'Custom partner'), ('INTERNAL', 'Internal')], max_length=40)),
                ('event_type', models.CharField(choices=[('BOOKING_CREATE', 'Booking create'), ('BOOKING_UPDATE', 'Booking update'), ('BOOKING_CANCEL', 'Booking cancel'), ('AVAILABILITY_SYNC', 'Availability sync'), ('PRODUCT_SYNC', 'Product sync'), ('UNKNOWN', 'Unknown')], default='BOOKING_CREATE', max_length=30)),
                ('external_booking_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('external_supplier_reference', models.CharField(blank=True, max_length=255)),
                ('source_endpoint', models.CharField(blank=True, max_length=255)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Received'), ('DUPLICATE', 'Duplicate'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('processing_notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='external_booking_reference',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='integration_provider',
            field=models.CharField(blank=True, choices=[('GET_YOUR_GUIDE', 'GetYourGuide'), ('VIATOR', 'Viator'), ('OTA_GENERIC', 'Generic OTA'), ('API_GENERIC', 'Generic API'), ('CUSTOM_PARTNER', 'Custom partner'), ('INTERNAL', 'Internal')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('integration_provider', ''), _negated=True), models.Q(('external_booking_reference', ''), _negated=True)), fields=('integration_provider', 'external_booking_reference'), name='booking_external_reference_unique'),
        ),
        migrations.AddConstraint(
            model_name='apiidempotencyrecord',
            constraint=models.UniqueConstraint(fields=('provider', 'event_type', 'idempotency_key'), name='api_idempotency_provider_event_key_unique'),
        ),
        migrations.AddField(
            model_name='externalproductmapping',
            name='participant_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_mappings', to='operations.productparticipantcategory'),
        ),
        migrations.AddField(
            model_name='externalproductmapping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to='operations.product'),
        ),
        migrations.AddField(
            model_name='inboundbookingpayload',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_payloads', to='operations.booking'),
        ),
        migrations.AddField(
            model_name='inboundbookingpayload',
            name='idempotency_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payloads', to='operations.apiidempotencyrecord'),
        ),
        migrations.AddField(
            model_name='inboundbookingpayload',
            name='product_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_payloads', to='operations.externalproductmapping'),
        ),
        migrations.AddField(
            model_name='inboundbookingpayload',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_payloads', to='operations.reservation'),
        ),
        migrations.AddConstraint(
            model_name='externalproductmapping',
            constraint=models.UniqueConstraint(fields=('provider', 'external_product_id', 'external_option_id', 'external_rate_id', 'external_category_code'), name='external_product_mapping_provider_reference_unique'),
        ),
        migrations.AddConstraint(
            model_name='externalproductmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('provider', 'product'), name='external_product_mapping_single_default_per_provider_product'),
        ),
        migrations.AddIndex(
            model_name='inboundbookingpayload',
            index=models.Index(fields=['provider', 'external_booking_reference'], name='inb_pay_provider_ref_idx'),
        ),
    ]
