# Generated by Django 6.0.3 on 2026-03-29 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reference_no',
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='internal_reference',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='txn_reference',
            field=models.CharField(blank=True, help_text='Transaction ID from the payment provider', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='narration',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('MPESA', 'MPesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
