# Generated by Django 6.0.3 on 2026-03-29 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_payment_reference_no_payment_exchange_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='internal_reference',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice_ref',
            field=models.CharField(blank=True, help_text="Supplier's Invoice or Receipt Number", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'MPesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ACCOMMODATION', 'Accommodation'), ('TRANSPORT', 'Transport / Vehicle Hire'), ('FUEL', 'Fuel'), ('GUIDE_FEE', 'Guide Fees / Allowances'), ('PARK_FEE', 'Park Entry Fees'), ('MEAL', 'Meals & Drinks'), ('OFFICE', 'Office Operations'), ('MARKETING', 'Marketing'), ('UTILITY', 'Utilities (Rent, Water, Power)'), ('SALARY', 'Salaries & Allowances'), ('REFUND', 'Client Refunds'), ('OTHER', 'Miscellaneous')], max_length=100),
        ),
    ]
