# Generated by Codex on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expense_exchange_rate_expense_internal_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('BALANCE', 'Balance Payment'), ('FULL', 'Full Payment')], default='DEPOSIT', max_length=20),
        ),
    ]
