# Generated by Django 6.0.3 on 2026-04-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ACCOMMODATION', 'Accommodation'), ('TRANSPORT', 'Transport / Vehicle Hire'), ('FUEL', 'Fuel'), ('GUIDE_FEE', 'Guide Fees / Allowances'), ('PARK_FEE', 'Park Entry Fees'), ('MEAL', 'Meals & Drinks'), ('OFFICE', 'Office Operations'), ('MARKETING', 'Marketing'), ('COMMISSION', 'Commission'), ('UTILITY', 'Utilities (Rent, Water, Power)'), ('SALARY', 'Salaries & Allowances'), ('REFUND', 'Client Refunds'), ('OTHER', 'Miscellaneous')], max_length=100),
        ),
    ]
